### PR TITLE
Update Import-and-Update.md

### PR DESCRIPTION
**Pull request by jeremy-rutman**
this would have been very useful for me in my own install

### CODE REVIEW

**Comment by lonvia** [comment]
The location of the website rather depends on how the webserver is set up. The import section doesn't make any assumptions about that. It should be mentioned in the 'Setting up the Webserver' sections in the installation instructions for specific OSses though. We kind of assume there that it is obvious from the config, which is not good.

**Comment by jeremy-rutman** [comment]
imho this can only help noobs such as myself .
The site http://localhost/nominatim/lookup.php   would work no matter the webserver setup, no?

**Comment by lonvia** [comment]
No. The example webserver setup deliberately creates an Alias for /nominatim so that the URL above works.

**Comment by lonvia** [comment]
The link is already mentioned in the Apache setup section, so closing this.

**Pull request closed without merging**
