### PR TITLE
Command line option to specify osm2pgsql process count

### PR DESCRIPTION
**Pull request by Shkarface**
This command line options is useful when importing full updates with --import-file
It allows setting the --number-processes command line of osm2pgsql to use more CPU for the import process

### CODE REVIEW

**Comment by lonvia** [comment]
The number of processes was set to 1 intentionally. The osm2pgsql import itself is not multithreaded (or rather it is but not in any way that is influenced by this parameter). The only phase that is parallel is indexing. In this phase a high number of threads tends to be counter-productive. In my experience it is better to increase the maintenance memory to make creating a single index faster than increasing the number of parallel threads.

**Comment by Shkarface** [comment]
@lonvia thank you for the explanation, in my case the update was really slow and i thought this might be the issue

**Comment by curiousercreative** [comment]
@lonvia issue should be closed?

**Comment by lonvia** [comment]
I hadn't initially seen that we are talking about updates here and meant to look into if the comment above is true for that too.

**Comment by lonvia** [comment]
So, same thing for updates. Closing.

**Pull request closed without merging**
