### PR TITLE
Support housenumber=0 in interpolations

### PR DESCRIPTION
**Pull request by mtmail**
fixes https://github.com/openstreetmap/Nominatim/issues/1287

### CODE REVIEW

**Comment by lonvia** [comment]
Any chance that you add a test case in `test/bdd/db/import/interpolation.feature`?

**Comment by mtmail** [comment]
@mtmail Added a BDD test case

**Comment by lonvia** [comment]
Now that test is failing in a very odd way. Maybe the 0 is interfering badly with the test harness?

**Comment by mtmail** [comment]
rebased with master, Travis tests pass now.

**Pull request merged**
