### PR TITLE
Display viewbox on map

### PR DESCRIPTION
**Pull request by mtmail**
fixes https://github.com/openstreetmap/Nominatim/issues/1061

URLSearchParams is not available (yet) in all browsers https://caniuse.com/#feat=urlsearchparams so I added a polyfill.

image

### CODE REVIEW

**Comment by lonvia** [comment]
Thanks!

**Comment by lonvia** [comment]
The example in #1058 still doesn't work because the order in viewbox is not as Leaflet expects it. Nominatim does not care about order.

**Comment by mtmail** [comment]
I see the viewbox. Adding ",roma" to the URL because currently a road in Naples is returned

https://nominatim.openstreetmap.org/search.php?q=viale+carnaro,roma&polygon_geojson=1&viewbox=12.51491%2C41.93361%2C12.53014%2C41.92962

**Comment by lonvia** [comment]
Indeed, I was just too far zoomed out so it got too small. All good.

**Pull request merged**
